# Generated by Django 4.0.8 on 2023-05-09 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('date', models.DateTimeField(auto_now_add=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('diagnosis', models.CharField(max_length=10)),
                ('radius_mean', models.CharField(max_length=10)),
                ('texture_mean', models.CharField(max_length=10)),
                ('perimeter_mean', models.CharField(max_length=10)),
                ('area_mean', models.CharField(max_length=10)),
                ('smoothness_mean', models.CharField(max_length=10)),
                ('compactness_mean', models.CharField(max_length=10)),
                ('concavity_mean', models.CharField(max_length=10)),
                ('concave_points_mean', models.CharField(max_length=10)),
                ('points_mean', models.CharField(max_length=10)),
                ('symmetry_mean', models.CharField(max_length=10)),
                ('fractal_dimension_mean', models.CharField(max_length=10)),
                ('radius_se', models.CharField(max_length=10)),
                ('texture_se', models.CharField(max_length=10)),
                ('perimeter_se', models.CharField(max_length=10)),
                ('area_se', models.CharField(max_length=10)),
                ('smoothness_se', models.CharField(max_length=10)),
                ('compactness_se', models.CharField(max_length=10)),
                ('concavity_se', models.CharField(max_length=10)),
                ('concave_points_se', models.CharField(max_length=10)),
                ('points_se', models.CharField(max_length=10)),
                ('symmetry_se', models.CharField(max_length=10)),
                ('fractal_dimension_se', models.CharField(max_length=10)),
                ('radius_worst', models.CharField(max_length=10)),
                ('texture_worst', models.CharField(max_length=10)),
                ('perimeter_worst', models.CharField(max_length=10)),
                ('area_worst', models.CharField(max_length=10)),
                ('smoothness_worst', models.CharField(max_length=10)),
                ('compactness_worst', models.CharField(max_length=10)),
                ('concavity_worst', models.CharField(max_length=10)),
                ('concave_points_worst', models.CharField(max_length=10)),
                ('points_worst', models.CharField(max_length=10)),
                ('symmetry_worst', models.CharField(max_length=10)),
                ('fractal_dimension_worst', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
